{
  "compatibilityLevel": 1550,
  "model": {
    "annotations": [
      {
        "name": "PBI_QueryOrder",
        "value": "[\"Nubank\",\"Arquivo de Amostra\",\"Parâmetro1\",\"Transformar o Arquivo de Exemplo\",\"Transformar Arquivo\"]"
      },
      {
        "name": "__PBI_TimeIntelligenceEnabled",
        "value": "1"
      },
      {
        "name": "PBIDesktopVersion",
        "value": "2.122.746.0 (23.10)"
      },
      {
        "name": "PBI_ProTooling",
        "value": "[\"DevMode\"]"
      }
    ],
    "culture": "pt-BR",
    "cultures": [
      {
        "name": "pt-BR",
        "linguisticMetadata": {
          "content": {
            "DynamicImprovement": "HighConfidence",
            "Language": "en-US",
            "Version": "1.0.0"
          },
          "contentType": "json"
        }
      }
    ],
    "dataAccessOptions": {
      "legacyRedirects": true,
      "returnErrorValuesAsNull": true
    },
    "defaultPowerBIDataSourceVersion": "powerBI_V3",
    "expressions": [
      {
        "name": "Arquivo de Amostra",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Folder.Files(\"G:\\Meu Drive\\Nubank\"),",
          "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Extension] = \".csv\")),",
          "    Navegação1 = #\"Linhas Filtradas\"{0}[Content]",
          "in",
          "    Navegação1"
        ],
        "kind": "m",
        "lineageTag": "8cfc4b6d-d9fe-4b56-933d-c831d0e58f88",
        "queryGroup": "Transformar Arquivo de Nubank\\Consultas Auxiliares"
      },
      {
        "name": "Parâmetro1",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Binary"
          }
        ],
        "expression": "#\"Arquivo de Amostra\" meta [IsParameterQuery=true, BinaryIdentifier=#\"Arquivo de Amostra\", Type=\"Binary\", IsParameterQueryRequired=true]",
        "kind": "m",
        "lineageTag": "84839087-bb25-4592-8092-49557e72b559",
        "queryGroup": "Transformar Arquivo de Nubank\\Consultas Auxiliares"
      },
      {
        "name": "Transformar o Arquivo de Exemplo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "expression": [
          "let",
          "    Fonte = Csv.Document(Parâmetro1,[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "    #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "in",
          "    #\"Cabeçalhos Promovidos\""
        ],
        "kind": "m",
        "lineageTag": "dc416641-fbe7-481a-915f-f56f141fe10e",
        "queryGroup": "Transformar Arquivo de Nubank"
      },
      {
        "name": "Transformar Arquivo",
        "annotations": [
          {
            "name": "PBI_ResultType",
            "value": "Function"
          }
        ],
        "expression": [
          "let",
          "    Fonte = (Parâmetro1) => let",
          "        Fonte = Csv.Document(Parâmetro1,[Delimiter=\",\", Columns=4, Encoding=65001, QuoteStyle=QuoteStyle.None]),",
          "        #\"Cabeçalhos Promovidos\" = Table.PromoteHeaders(Fonte, [PromoteAllScalars=true])",
          "    in",
          "        #\"Cabeçalhos Promovidos\"",
          "in",
          "    Fonte"
        ],
        "kind": "m",
        "lineageTag": "ce140c09-9333-4c5c-b798-7dc5b61be12f",
        "mAttributes": "[ FunctionQueryBinding = \"{\"\"exemplarFormulaName\"\":\"\"Transformar o Arquivo de Exemplo\"\"}\" ]",
        "queryGroup": "Transformar Arquivo de Nubank\\Consultas Auxiliares"
      }
    ],
    "queryGroups": [
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Nubank"
      },
      {
        "annotations": [
          {
            "name": "PBI_QueryGroupOrder",
            "value": "0"
          }
        ],
        "folder": "Transformar Arquivo de Nubank\\Consultas Auxiliares"
      }
    ],
    "relationships": [
      {
        "name": "165dc550-47d3-4c48-9f58-f443411c0bb1",
        "fromColumn": "Data",
        "fromTable": "Nubank",
        "joinOnDateBehavior": "datePartOnly",
        "toColumn": "Date",
        "toTable": "LocalDateTable_7ffc8fa6-3585-4b3f-b8cb-b77e3f69fe3d"
      }
    ],
    "sourceQueryCulture": "pt-BR",
    "tables": [
      {
        "name": "Nubank",
        "annotations": [
          {
            "name": "PBI_NavigationStepName",
            "value": "Navegação"
          },
          {
            "name": "PBI_ResultType",
            "value": "Table"
          }
        ],
        "columns": [
          {
            "name": "Nome da Origem",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "1b291134-7c50-471a-97d2-d85f5bfcfd91",
            "sourceColumn": "Nome da Origem",
            "summarizeBy": "none"
          },
          {
            "name": "Identificador",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "ca76cc19-893b-4e0b-9a66-090401a814ab",
            "sourceColumn": "Identificador",
            "summarizeBy": "none"
          },
          {
            "name": "Data",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "UnderlyingDateTimeDataType",
                "value": "Date"
              }
            ],
            "dataType": "dateTime",
            "formatString": "Long Date",
            "lineageTag": "f2a24c17-3c33-49cf-bb6f-a8bcadd27503",
            "sourceColumn": "Data",
            "summarizeBy": "none",
            "variations": [
              {
                "name": "Variation",
                "defaultHierarchy": {
                  "hierarchy": "Hierarquia de datas",
                  "table": "LocalDateTable_7ffc8fa6-3585-4b3f-b8cb-b77e3f69fe3d"
                },
                "isDefault": true,
                "relationship": "165dc550-47d3-4c48-9f58-f443411c0bb1"
              }
            ]
          },
          {
            "name": "Tipo de Transacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "339f05d3-5566-41f8-9997-837812b7fdc8",
            "sourceColumn": "Tipo de Transacao",
            "summarizeBy": "none"
          },
          {
            "name": "Descrição.2",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "913ee255-9dca-4440-8e12-8cf1346761f4",
            "sourceColumn": "Descrição.2",
            "summarizeBy": "none"
          },
          {
            "name": "Personalizar",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              }
            ],
            "dataType": "string",
            "lineageTag": "79b02bf1-2ca1-44d6-b3d5-686480790d73",
            "sourceColumn": "Personalizar",
            "summarizeBy": "none"
          },
          {
            "name": "Valor Transacao",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "Automatic"
              },
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "dataType": "decimal",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "3990314d-dfe3-4dc7-8189-0f07f9d49ad5",
            "sourceColumn": "Valor Transacao",
            "summarizeBy": "sum"
          }
        ],
        "lineageTag": "4167e8b3-d426-4532-99dd-7edacc9a67e7",
        "measures": [
          {
            "name": "Medida",
            "annotations": [
              {
                "name": "PBI_FormatHint",
                "value": "{\"currencyCulture\":\"pt-BR\"}"
              }
            ],
            "expression": "AVERAGE(Nubank[Valor Transacao])+35",
            "formatString": "\"R$\"\\ #,0.###############;-\"R$\"\\ #,0.###############;\"R$\"\\ #,0.###############",
            "lineageTag": "b5d5fc58-02b1-4b88-a953-d1a6ed3665b6"
          }
        ],
        "partitions": [
          {
            "name": "Nubank",
            "mode": "import",
            "source": {
              "expression": [
                "let",
                "    Fonte = Folder.Files(\"G:\\Meu Drive\\Nubank\"),",
                "    #\"Linhas Filtradas\" = Table.SelectRows(Fonte, each ([Extension] = \".csv\")),",
                "    #\"Arquivos Ocultos Filtrados1\" = Table.SelectRows(#\"Linhas Filtradas\", each [Attributes]?[Hidden]? <> true),",
                "    #\"Invocar Função Personalizada1\" = Table.AddColumn(#\"Arquivos Ocultos Filtrados1\", \"Transformar Arquivo\", each #\"Transformar Arquivo\"([Content])),",
                "    #\"Colunas Renomeadas1\" = Table.RenameColumns(#\"Invocar Função Personalizada1\", {\"Name\", \"Nome da Origem\"}),",
                "    #\"Outras Colunas Removidas1\" = Table.SelectColumns(#\"Colunas Renomeadas1\", {\"Nome da Origem\", \"Transformar Arquivo\"}),",
                "    #\"Coluna de Tabela Expandida1\" = Table.ExpandTableColumn(#\"Outras Colunas Removidas1\", \"Transformar Arquivo\", Table.ColumnNames(#\"Transformar Arquivo\"(#\"Arquivo de Amostra\"))),",
                "    #\"Tipo Alterado\" = Table.TransformColumnTypes(#\"Coluna de Tabela Expandida1\",{{\"Nome da Origem\", type text}, {\"Data\", type date}, {\"Valor\", type number}, {\"Identificador\", type text}, {\"Descrição\", type text}}),",
                "    #\"Duplicatas Removidas\" = Table.Distinct(#\"Tipo Alterado\", {\"Identificador\"}),",
                "    #\"Dividir Coluna por Delimitador\" = Table.SplitColumn(#\"Duplicatas Removidas\", \"Descrição\", Splitter.SplitTextByEachDelimiter({\"-\"}, QuoteStyle.Csv, false), {\"Descrição.1\", \"Descrição.2\"}),",
                "    #\"Tipo Alterado1\" = Table.TransformColumnTypes(#\"Dividir Coluna por Delimitador\",{{\"Descrição.1\", type text}, {\"Descrição.2\", type text}}),",
                "    #\"Colunas Renomeadas\" = Table.RenameColumns(#\"Tipo Alterado1\",{{\"Descrição.1\", \"Tipo de Transacao\"}}),",
                "    #\"Texto Aparado\" = Table.TransformColumns(#\"Colunas Renomeadas\",{{\"Tipo de Transacao\", Text.Trim, type text}}),",
                "    #\"Valor Substituído2\" = Table.ReplaceValue(#\"Texto Aparado\",\" ANALYTICS BUSINESS I - 35.715.967/0001-34 - BANCO INTER (0077) Agência: 1 Conta: 4692067-6\",\"Salário\",Replacer.ReplaceText,{\"Descrição.2\"}),",
                "    #\"Valor Substituído\" = Table.ReplaceValue(#\"Valor Substituído2\",\" PABLO ROBERTO BRAVO - 35.715.967/0001-34 - BANCO INTER (0077) Agência: 1 Conta: 4692067-6\",\"Salário\",Replacer.ReplaceText,{\"Descrição.2\"}),",
                "    #\"Linhas Filtradas1\" = Table.SelectRows(#\"Valor Substituído\", each ([Nome da Origem] <> \"NU_71985546_01SET2022_30SET2022.csv\")),",
                "    #\"Valor Substituído1\" = Table.ReplaceValue(#\"Linhas Filtradas1\",\" ARMAZEM PARAISO - 90.958.489/0001-00 - ITAÚ UNIBANCO S.A. (0341) Agência: 9225 Conta: 99857-5\",\"Supermercado Paraiso\",Replacer.ReplaceText,{\"Descrição.2\"}),",
                "    #\"Valor Substituído3\" = Table.ReplaceValue(#\"Valor Substituído1\",\" Uber - 17.895.646/0001-87 - EBANX IP LTDA. Agência: 1 Conta: 1000752180-1\",\"Uber\",Replacer.ReplaceText,{\"Descrição.2\"}),",
                "    #\"Coluna Condicional Adicionada\" = Table.AddColumn(#\"Valor Substituído3\", \"Personalizar\", each if Text.Contains([Descrição.2], \"99*\") then \"UBER/99\" else if Text.Contains([Descrição.2], \"Ifd*\") then \"Ifood\" else if Text.Contains([Descrição.2], \"FILHOS ADM E INTERM\") then \"Aluguel\" else if Text.Contains([Descrição.2], \"Ifood\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Lanche\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Haus\") then \"Ifood\" else if Text.Contains([Descrição.2], \"CEEE\") then \"Energia Elétrica\" else if Text.Contains([Descrição.2], \"CLARO\") then \"Claro\" else if Text.Contains([Descrição.2], \"Supermercado\") then \"Supermercado\" else if Text.Contains([Descrição.2], \"Burger King\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Cineflix\") then \"Lazer\" else if Text.Contains([Descrição.2], \"Pag*Galpao\") then \"Lazer\" else if Text.Contains([Descrição.2], \"Teia Ecologica\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Diade\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Ebw*Spotify\") then \"Streaming\" else if Text.Contains([Descrição.2], \"Amazonprimebr\") then \"Streaming\" else if Text.Contains([Descrição.2], \"Riachuelo\") then \"Roupas\" else if Text.Contains([Descrição.2], \"Mk Pelotas Shopping\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Padaria Alecrim\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Nacional Lobo da Costa\") then \"Supermercado\" else if Text.Contains([Descrição.2], \"Ferragem Etc e Tal\") then \"Ferragem\" else if Text.Contains([Descrição.2], \"Panvel\") then \"Farmácia\" else if Text.Contains([Descrição.2], \"Avicola Carve\") then \"Gatos\" else if Text.Contains([Descrição.2], \"Dom Pastelo\") then \"Ifood\" else if Text.Contains([Descrição.2], \"Petz\") then \"Gatos\" else if Text.Contains([Descrição.2], \"Salário\") then \"Salário\" else if Text.Contains([Descrição.2], \"Uber\") then \"UBER/99\" else if Text.Contains([Descrição.2], \"15.436.940/0001-03\") then \"Compras\" else if Text.Contains([Descrição.2], \"38.372.267/0001-82\") then \"Compras\" else if Text.Contains([Descrição.2], \"00.394.460/0058-87\") then \"MEI\" else if Text.Contains([Descrição.2], \"Sympla\") then \"Lazer\" else if Text.Contains([Descrição.2], \"Breno grellert\") then \"Contas Cartão Pai\" else if Text.Contains([Descrição.2], \"Consorcio de Transport\") then \"Ônibus\" else if Text.Contains([Descrição.2], \"CIA ESTADUAL\") then \"Energia Elétrica\" else if Text.Contains([Descrição.2], \"BANCO PAN SA\") then \"Reneg. Pan\" else if Text.Contains([Descrição.2], \"PANVEL\") then \"Farmácia\" else if Text.Contains([Descrição.2], \"RUDI BONOW\") then \"Supermercado\" else if Text.Contains([Descrição.2], \"FERRAGEM\") then \"Ferragem\" else if Text.Contains([Descrição.2], \"Dom Netto\") then \"Ifood\" else if Text.Contains([Descrição.2], \"ISAIR CARDOSO\") then \"Supermercado\" else \"Outros\"),",
                "    #\"Linhas Filtradas4\" = Table.SelectRows(#\"Coluna Condicional Adicionada\", each ([Tipo de Transacao] <> \"Valor Mensal Programado\")),",
                "    #\"Linhas Filtradas2\" = Table.SelectRows(#\"Linhas Filtradas4\", each ([Tipo de Transacao] <> \"Aplicação Fundo\" and [Tipo de Transacao] <> \"Resgate Fundo\")),",
                "    #\"Erros Substituídos\" = Table.ReplaceErrorValues(#\"Linhas Filtradas2\", {{\"Personalizar\", \"Outros\"}}),",
                "    #\"Tipo Alterado2\" = Table.TransformColumnTypes(#\"Erros Substituídos\",{{\"Valor\", type number}}),",
                "    #\"Tipo Alterado3\" = Table.TransformColumnTypes(#\"Tipo Alterado2\",{{\"Personalizar\", type text}}),",
                "    #\"Personalização Adicionada\" = Table.AddColumn(#\"Tipo Alterado3\", \"Personalizar.1\", each [Valor]/100),",
                "    #\"Tipo Alterado4\" = Table.TransformColumnTypes(#\"Personalização Adicionada\",{{\"Personalizar.1\", Currency.Type}}),",
                "    #\"Colunas Renomeadas2\" = Table.RenameColumns(#\"Tipo Alterado4\",{{\"Personalizar.1\", \"Valor Transacao\"}}),",
                "    #\"Colunas Removidas\" = Table.RemoveColumns(#\"Colunas Renomeadas2\",{\"Valor\"}),",
                "    #\"Colunas Reordenadas\" = Table.ReorderColumns(#\"Colunas Removidas\",{\"Nome da Origem\", \"Identificador\", \"Data\", \"Tipo de Transacao\", \"Descrição.2\", \"Personalizar\", \"Valor Transacao\"})",
                "in",
                "    #\"Colunas Reordenadas\""
              ],
              "type": "m"
            }
          }
        ]
      },
      {
        "name": "DateTableTemplate_8721ca34-96ea-4198-b5c3-411495d99399",
        "annotations": [
          {
            "name": "__PBI_TemplateDateTable",
            "value": "true"
          },
          {
            "name": "DefaultItem",
            "value": "DateHierarchy"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "c9eebf94-8d7a-411a-9e8a-51cbcb9f3420",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "bc0516a6-cdcb-4557-9029-a5b8132e4ed9",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "5638b2f8-0862-442f-80ae-86eccc367f4f",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "87386f76-d1a4-4da1-b612-df764e17eaec",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "659dece5-cba0-404e-8b56-cf36db30c988",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "32e035e7-1b23-481a-86f8-dcdd77a62834",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "347a84ea-d4fd-47d0-8668-bc3be31b180f",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "116111b4-c207-497a-b1c2-a05a91eab18b",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "562b34f2-c74a-447e-a3c9-76679153fdae",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "205b305c-3bb0-45f3-8dca-95e3962213d5",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "f3926d3a-f27f-448a-a8fa-956849e1398b",
                "ordinal": 3
              }
            ],
            "lineageTag": "5a842206-3368-4683-b2a8-f87522803da5"
          }
        ],
        "isHidden": true,
        "isPrivate": true,
        "lineageTag": "67dc9455-4f4c-492d-aabc-7e2e6f9c474c",
        "partitions": [
          {
            "name": "DateTableTemplate_8721ca34-96ea-4198-b5c3-411495d99399",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(2015,1,1), Date(2015,1,1))",
              "type": "calculated"
            }
          }
        ]
      },
      {
        "name": "LocalDateTable_7ffc8fa6-3585-4b3f-b8cb-b77e3f69fe3d",
        "annotations": [
          {
            "name": "__PBI_LocalDateTable",
            "value": "true"
          }
        ],
        "columns": [
          {
            "name": "Date",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              }
            ],
            "dataCategory": "PaddedDateTableDates",
            "dataType": "dateTime",
            "isHidden": true,
            "isNameInferred": true,
            "lineageTag": "f115368e-c652-47b7-8fdb-e62bb7532216",
            "sourceColumn": "[Date]",
            "summarizeBy": "none",
            "type": "calculatedTableColumn"
          },
          {
            "name": "Ano",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Year"
              }
            ],
            "dataCategory": "Years",
            "dataType": "int64",
            "expression": "YEAR([Date])",
            "isHidden": true,
            "lineageTag": "6e76c3ce-d6a6-40b0-af98-a44a9b098886",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "MonthNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "MonthNumber"
              }
            ],
            "dataCategory": "MonthOfYear",
            "dataType": "int64",
            "expression": "MONTH([Date])",
            "isHidden": true,
            "lineageTag": "ff2ff166-a5ad-47a6-852c-fdb6408a1f14",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Mês",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Month"
              }
            ],
            "dataCategory": "Months",
            "dataType": "string",
            "expression": "FORMAT([Date], \"MMMM\")",
            "isHidden": true,
            "lineageTag": "9ff8e79a-9add-4643-bfc3-85fd6a5f980a",
            "sortByColumn": "MonthNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "QuarterNo",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "QuarterNumber"
              }
            ],
            "dataCategory": "QuarterOfYear",
            "dataType": "int64",
            "expression": "INT(([MonthNo] + 2) / 3)",
            "isHidden": true,
            "lineageTag": "b67a75f6-8125-4f5e-846e-747349e02873",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Trimestre",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Quarter"
              }
            ],
            "dataCategory": "Quarters",
            "dataType": "string",
            "expression": "\"Trim \" & [QuarterNo]",
            "isHidden": true,
            "lineageTag": "fb015eae-6da4-4c33-9dc4-507ccfdc0913",
            "sortByColumn": "QuarterNo",
            "summarizeBy": "none",
            "type": "calculated"
          },
          {
            "name": "Dia",
            "annotations": [
              {
                "name": "SummarizationSetBy",
                "value": "User"
              },
              {
                "name": "TemplateId",
                "value": "Day"
              }
            ],
            "dataCategory": "DayOfMonth",
            "dataType": "int64",
            "expression": "DAY([Date])",
            "isHidden": true,
            "lineageTag": "5ecca3ee-7cb2-496d-972c-690c64397baf",
            "summarizeBy": "none",
            "type": "calculated"
          }
        ],
        "hierarchies": [
          {
            "name": "Hierarquia de datas",
            "annotations": [
              {
                "name": "TemplateId",
                "value": "DateHierarchy"
              }
            ],
            "levels": [
              {
                "name": "Ano",
                "column": "Ano",
                "lineageTag": "ff610f2b-26b8-4a72-afc3-e7df2203f005",
                "ordinal": 0
              },
              {
                "name": "Trimestre",
                "column": "Trimestre",
                "lineageTag": "91cc64e7-c561-4cb6-b95f-4168ecf106dc",
                "ordinal": 1
              },
              {
                "name": "Mês",
                "column": "Mês",
                "lineageTag": "55eb6857-9a9c-44e0-89ee-68f76398de41",
                "ordinal": 2
              },
              {
                "name": "Dia",
                "column": "Dia",
                "lineageTag": "6f43a3ec-31eb-4019-b37f-af77e0d2f95f",
                "ordinal": 3
              }
            ],
            "lineageTag": "bef3b043-3f73-417c-bd09-53d42f5380b8"
          }
        ],
        "isHidden": true,
        "lineageTag": "f19acce6-aeb5-4775-a285-85cb1b969642",
        "partitions": [
          {
            "name": "LocalDateTable_7ffc8fa6-3585-4b3f-b8cb-b77e3f69fe3d",
            "mode": "import",
            "source": {
              "expression": "Calendar(Date(Year(MIN('Nubank'[Data])), 1, 1), Date(Year(MAX('Nubank'[Data])), 12, 31))",
              "type": "calculated"
            }
          }
        ],
        "showAsVariationsOnly": true
      }
    ]
  }
}